# Capture Settings
MAX_MOOD_ENTRIES = 3
MAX_JOURNAL_ENTRIES = 1

# Review Chart Settings
MOOD_PRIMARY_COLOR = "#27ae60"
MOOD_BACKGROUND_COLOR = "#fff"
MOOD_STROKE_WIDTH = 0 
MOOD_ANIMATION_DURATION = 1000
MOOD_ANIMATION_EASING = 'in'
MOOD_LEGEND_POSITION = 'none'

JOURNAL_PRIMARY_COLOR = "#f39c12"
JOURNAL_BACKGROUND_COLOR = "#fff"
JOURNAL_STROKE_WIDTH = 0 
JOURNAL_ANIMATION_DURATION = 1000
JOURNAL_ANIMATION_EASING = 'in'
JOURNAL_LEGEND_POSITION = 'none'