# Capture Settings
MAX_MOOD_ENTRIES = 3
MAX_JOURNAL_ENTRIES = 1

# Review Chart Settings 
JOURNAL_PRIMARY_COLOR = "#f39c12"
JOURNAL_BACKGROUND_COLOR = "#fff"
JOURNAL_STROKE_WIDTH = 0 
JOURNAL_ANIMATION_DURATION = 1000
JOURNAL_ANIMATION_EASING = 'in'
JOURNAL_LEGEND_POSITION = 'none'