# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
# stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
# stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

FB_ID: "834134359957692"
FB_SECRET: "8068ef2c524b4181726f6edd343cad4c"

GOOGLE_ID: "453255438964-ci57ulnphna265qgqlkp1sav4had1g0t.apps.googleusercontent.com"
GOOGLE_SECRET: "7zZtul1UFlUf-qjkowV2iN71"

EMAIL_USERNAME: "postmaster@mg.thrivestreams.com"
EMAIL_PASSWORD: "3c8352e4f91008bcb603f12a776540fb"

SEGMENT_IO_WRITE_KEY: "qamACa9VfmVQTd4KqbOyPNj8aBZnnzPI"

PARSE_APPLICATION_ID: "4mICPjquNch3SFBRTJNGhYU1SLbY8juJiGRqm6Bb"
PARSE_API_KEY: "E9MAWtQMN3a3S5lYLD9fcGN4GC9HfufB2dmPjZOq"

SECRET_KEY_BASE: "6e15e3eb8ab804a948ac15561248e96da16844cc747a5f42d1745faf96ea4c829e21f05a28b5fdf99cc3d2ac9001f7b61350f1eabda1ef4f0bdb5cbd0472573a"
