development:
  app_id: ENV['PARSE_ID']
  master_key: ENV['PARSE_API_KEY']

test:
  app_id: ENV['PARSE_ID']
  master_key: ENV['PARSE_API_KEY']

production:
  app_id: ENV['PARSE_ID']
  master_key: ENV['PARSE_API_KEY']