require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PassiveSleepsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PassiveSleep. As you add validations to PassiveSleep, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PassiveSleepsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all passive_sleeps as @passive_sleeps" do
      passive_sleep = PassiveSleep.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:passive_sleeps)).to eq([passive_sleep])
    end
  end

  describe "GET #show" do
    it "assigns the requested passive_sleep as @passive_sleep" do
      passive_sleep = PassiveSleep.create! valid_attributes
      get :show, {:id => passive_sleep.to_param}, valid_session
      expect(assigns(:passive_sleep)).to eq(passive_sleep)
    end
  end

  describe "GET #new" do
    it "assigns a new passive_sleep as @passive_sleep" do
      get :new, {}, valid_session
      expect(assigns(:passive_sleep)).to be_a_new(PassiveSleep)
    end
  end

  describe "GET #edit" do
    it "assigns the requested passive_sleep as @passive_sleep" do
      passive_sleep = PassiveSleep.create! valid_attributes
      get :edit, {:id => passive_sleep.to_param}, valid_session
      expect(assigns(:passive_sleep)).to eq(passive_sleep)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PassiveSleep" do
        expect {
          post :create, {:passive_sleep => valid_attributes}, valid_session
        }.to change(PassiveSleep, :count).by(1)
      end

      it "assigns a newly created passive_sleep as @passive_sleep" do
        post :create, {:passive_sleep => valid_attributes}, valid_session
        expect(assigns(:passive_sleep)).to be_a(PassiveSleep)
        expect(assigns(:passive_sleep)).to be_persisted
      end

      it "redirects to the created passive_sleep" do
        post :create, {:passive_sleep => valid_attributes}, valid_session
        expect(response).to redirect_to(PassiveSleep.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved passive_sleep as @passive_sleep" do
        post :create, {:passive_sleep => invalid_attributes}, valid_session
        expect(assigns(:passive_sleep)).to be_a_new(PassiveSleep)
      end

      it "re-renders the 'new' template" do
        post :create, {:passive_sleep => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested passive_sleep" do
        passive_sleep = PassiveSleep.create! valid_attributes
        put :update, {:id => passive_sleep.to_param, :passive_sleep => new_attributes}, valid_session
        passive_sleep.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested passive_sleep as @passive_sleep" do
        passive_sleep = PassiveSleep.create! valid_attributes
        put :update, {:id => passive_sleep.to_param, :passive_sleep => valid_attributes}, valid_session
        expect(assigns(:passive_sleep)).to eq(passive_sleep)
      end

      it "redirects to the passive_sleep" do
        passive_sleep = PassiveSleep.create! valid_attributes
        put :update, {:id => passive_sleep.to_param, :passive_sleep => valid_attributes}, valid_session
        expect(response).to redirect_to(passive_sleep)
      end
    end

    context "with invalid params" do
      it "assigns the passive_sleep as @passive_sleep" do
        passive_sleep = PassiveSleep.create! valid_attributes
        put :update, {:id => passive_sleep.to_param, :passive_sleep => invalid_attributes}, valid_session
        expect(assigns(:passive_sleep)).to eq(passive_sleep)
      end

      it "re-renders the 'edit' template" do
        passive_sleep = PassiveSleep.create! valid_attributes
        put :update, {:id => passive_sleep.to_param, :passive_sleep => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested passive_sleep" do
      passive_sleep = PassiveSleep.create! valid_attributes
      expect {
        delete :destroy, {:id => passive_sleep.to_param}, valid_session
      }.to change(PassiveSleep, :count).by(-1)
    end

    it "redirects to the passive_sleeps list" do
      passive_sleep = PassiveSleep.create! valid_attributes
      delete :destroy, {:id => passive_sleep.to_param}, valid_session
      expect(response).to redirect_to(passive_sleeps_url)
    end
  end

end
