require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PreDefinedCardsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PreDefinedCard. As you add validations to PreDefinedCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PreDefinedCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all pre_defined_cards as @pre_defined_cards" do
      pre_defined_card = PreDefinedCard.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pre_defined_cards)).to eq([pre_defined_card])
    end
  end

  describe "GET #show" do
    it "assigns the requested pre_defined_card as @pre_defined_card" do
      pre_defined_card = PreDefinedCard.create! valid_attributes
      get :show, {:id => pre_defined_card.to_param}, valid_session
      expect(assigns(:pre_defined_card)).to eq(pre_defined_card)
    end
  end

  describe "GET #new" do
    it "assigns a new pre_defined_card as @pre_defined_card" do
      get :new, {}, valid_session
      expect(assigns(:pre_defined_card)).to be_a_new(PreDefinedCard)
    end
  end

  describe "GET #edit" do
    it "assigns the requested pre_defined_card as @pre_defined_card" do
      pre_defined_card = PreDefinedCard.create! valid_attributes
      get :edit, {:id => pre_defined_card.to_param}, valid_session
      expect(assigns(:pre_defined_card)).to eq(pre_defined_card)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PreDefinedCard" do
        expect {
          post :create, {:pre_defined_card => valid_attributes}, valid_session
        }.to change(PreDefinedCard, :count).by(1)
      end

      it "assigns a newly created pre_defined_card as @pre_defined_card" do
        post :create, {:pre_defined_card => valid_attributes}, valid_session
        expect(assigns(:pre_defined_card)).to be_a(PreDefinedCard)
        expect(assigns(:pre_defined_card)).to be_persisted
      end

      it "redirects to the created pre_defined_card" do
        post :create, {:pre_defined_card => valid_attributes}, valid_session
        expect(response).to redirect_to(PreDefinedCard.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved pre_defined_card as @pre_defined_card" do
        post :create, {:pre_defined_card => invalid_attributes}, valid_session
        expect(assigns(:pre_defined_card)).to be_a_new(PreDefinedCard)
      end

      it "re-renders the 'new' template" do
        post :create, {:pre_defined_card => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pre_defined_card" do
        pre_defined_card = PreDefinedCard.create! valid_attributes
        put :update, {:id => pre_defined_card.to_param, :pre_defined_card => new_attributes}, valid_session
        pre_defined_card.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pre_defined_card as @pre_defined_card" do
        pre_defined_card = PreDefinedCard.create! valid_attributes
        put :update, {:id => pre_defined_card.to_param, :pre_defined_card => valid_attributes}, valid_session
        expect(assigns(:pre_defined_card)).to eq(pre_defined_card)
      end

      it "redirects to the pre_defined_card" do
        pre_defined_card = PreDefinedCard.create! valid_attributes
        put :update, {:id => pre_defined_card.to_param, :pre_defined_card => valid_attributes}, valid_session
        expect(response).to redirect_to(pre_defined_card)
      end
    end

    context "with invalid params" do
      it "assigns the pre_defined_card as @pre_defined_card" do
        pre_defined_card = PreDefinedCard.create! valid_attributes
        put :update, {:id => pre_defined_card.to_param, :pre_defined_card => invalid_attributes}, valid_session
        expect(assigns(:pre_defined_card)).to eq(pre_defined_card)
      end

      it "re-renders the 'edit' template" do
        pre_defined_card = PreDefinedCard.create! valid_attributes
        put :update, {:id => pre_defined_card.to_param, :pre_defined_card => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested pre_defined_card" do
      pre_defined_card = PreDefinedCard.create! valid_attributes
      expect {
        delete :destroy, {:id => pre_defined_card.to_param}, valid_session
      }.to change(PreDefinedCard, :count).by(-1)
    end

    it "redirects to the pre_defined_cards list" do
      pre_defined_card = PreDefinedCard.create! valid_attributes
      delete :destroy, {:id => pre_defined_card.to_param}, valid_session
      expect(response).to redirect_to(pre_defined_cards_url)
    end
  end

end
